=== jamescatania1/voxel-raymarching/json/glTF.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "glTF.schema.json",
    "title": "glTF",
    "type": "object",
    "description": "The root object for a glTF asset.",
    "allOf": [
        {
            "$ref": "glTFProperty.schema.json"
        }
    ],
    "properties": {
        "extensionsUsed": {
            "type": "array",
            "description": "Names of glTF extensions used in this asset.",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "extensionsRequired": {
            "type": "array",
            "description": "Names of glTF extensions required to properly load this asset.",
            "items": {
                "type": "string"
            },
            "uniqueItems": true,
            "minItems": 1
        },
        "accessors": {
            "type": "array",
            "description": "An array of accessors.",
            "items": {
                "$ref": "accessor.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of accessors.  An accessor is a typed view into a bufferView."
        },
        "animations": {
            "type": "array",
            "description": "An array of keyframe animations.",
            "items": {
                "$ref": "animation.schema.json"
            },
            "minItems": 1
        },
        "asset": {
            "allOf": [
                {
                    "$ref": "asset.schema.json"
                }
            ],
            "description": "Metadata about the glTF asset."
        },
        "buffers": {
            "type": "array",
            "description": "An array of buffers.",
            "items": {
                "$ref": "buffer.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of buffers.  A buffer points to binary geometry, animation, or skins."
        },
        "bufferViews": {
            "type": "array",
            "description": "An array of bufferViews.",
            "items": {
                "$ref": "bufferView.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of bufferViews.  A bufferView is a view into a buffer generally representing a subset of the buffer."
        },
        "cameras": {
            "type": "array",
            "description": "An array of cameras.",
            "items": {
                "$ref": "camera.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of cameras.  A camera defines a projection matrix."
        },
        "images": {
            "type": "array",
            "description": "An array of images.",
            "items": {
                "$ref": "image.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of images.  An image defines data used to create a texture."
        },
        "materials": {
            "type": "array",
            "description": "An array of materials.",
            "items": {
                "$ref": "material.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of materials.  A material defines the appearance of a primitive."
        },
        "meshes": {
            "type": "array",
            "description": "An array of meshes.",
            "items": {
                "$ref": "mesh.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of meshes.  A mesh is a set of primitives to be rendered."
        },
        "nodes": {
            "type": "array",
            "description": "An array of nodes.",
            "items": {
                "$ref": "node.schema.json"
            },
            "minItems": 1
        },
        "samplers": {
            "type": "array",
            "description": "An array of samplers.",
            "items": {
                "$ref": "sampler.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of samplers.  A sampler contains properties for texture filtering and wrapping modes."
        },
        "scene": {
            "allOf": [
                {
                    "$ref": "glTFid.schema.json"
                }
            ],
            "description": "The index of the default scene.",
            "gltf_detailedDescription": "The index of the default scene.  This property **MUST NOT** be defined, when `scenes` is undefined."
        },
        "scenes": {
            "type": "array",
            "description": "An array of scenes.",
            "items": {
                "$ref": "scene.schema.json"
            },
            "minItems": 1
        },
        "skins": {
            "type": "array",
            "description": "An array of skins.",
            "items": {
                "$ref": "skin.schema.json"
            },
            "minItems": 1,
            "gltf_detailedDescription": "An array of skins.  A skin is defined by joints and matrices."
        },
        "textures": {
            "type": "array",
            "description": "An array of textures.",
            "items": {
                "$ref": "texture.schema.json"
            },
            "minItems": 1
        },
        "extensions": {},
        "extras": {}
    },
    "dependencies": {
        "scene": [
            "scenes"
        ]
    },
    "required": [
        "asset"
    ]
}

=== jamescatania1/voxel-raymarching/json/t.json
{
    "accessors": [
        {
            "bufferView": 0,
            "componentType": 5126,
            "count": 555,
            "max": [
                1.3671875,
                0.984375,
                0.8515625
            ],
            "min": [
                -1.3671875,
                -0.984375,
                -0.8515625
            ],
            "type": "VEC3"
        },
        {
            "bufferView": 1,
            "componentType": 5126,
            "count": 555,
            "type": "VEC3"
        },
        {
            "bufferView": 2,
            "componentType": 5126,
            "count": 555,
            "type": "VEC2"
        },
        {
            "bufferView": 3,
            "componentType": 5123,
            "count": 2904,
            "type": "SCALAR"
        }
    ],
    "asset": {
        "generator": "Khronos glTF Blender I/O v5.0.21",
        "version": "2.0"
    },
    "bufferViews": [
        {
            "buffer": 0,
            "byteLength": 6660,
            "byteOffset": 0,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 6660,
            "byteOffset": 6660,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 4440,
            "byteOffset": 13320,
            "target": 34962
        },
        {
            "buffer": 0,
            "byteLength": 5808,
            "byteOffset": 17760,
            "target": 34963
        }
    ],
    "buffers": [
        {
            "byteLength": 23568
        }
    ],
    "materials": [
        {
            "doubleSided": true,
            "name": "Material.001",
            "pbrMetallicRoughness": {
                "baseColorFactor": [
                    0.8000074625015259,
                    0.06889203935861588,
                    0.07974385470151901,
                    1
                ],
                "metallicFactor": 0,
                "roughnessFactor": 0.5
            }
        }
    ],
    "meshes": [
        {
            "name": "Suzanne",
            "primitives": [
                {
                    "attributes": {
                        "NORMAL": 1,
                        "POSITION": 0,
                        "TEXCOORD_0": 2
                    },
                    "indices": 3,
                    "material": 0
                }
            ]
        }
    ],
    "nodes": [
        {
            "mesh": 0,
            "name": "Suzanne"
        }
    ],
    "scene": 0,
    "scenes": [
        {
            "name": "Scene",
            "nodes": [
                0
            ]
        }
    ]
}
